apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep-exempt
  namespace: k8s-resource-validator
  labels:
    resources.gardener.cloud/managed-by: gardener
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "1000000"
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
